version: 0.1

phases:
    build:
        commands:
            - aws deploy push --region ap-northeast-1 --application-name stored_resources --s3-location s3://storedresources-codebuild/app.zip --source app
artifacts:
    files:
        - '**/*'
    base-directory: app
    name: app.zip
