version: "3"
services:
  app:
    build:
      context: "docker/"
    ports:
      - 80:80
    volumes:
      - "./src/:/var/www/html"
      - "./docker/httpd.conf:/etc/httpd/conf/httpd.conf"
volumes:
  storage:
