version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - 80:80
    volumes:
      - "./src/app/:/var/www/html/app"
      - "./docker/httpd.conf:/etc/httpd/conf/httpd.conf"
volumes:
  storage:
