version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.9
    steps:
      - checkout

      - run:
          command: |
            composer install --ignore-platform-reqs --no-scripts

      - run:
          command: |
            vendor/bin/phpunit src/tests/
  deploy:
    docker:
      - image: circleci/php:7.2.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - ${FPRINT}

      - run:
          command: |
            ssh -o "StrictHostKeyChecking no" ${SSH_USER}@${SSH_HOST} ${DEPLOYER}

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - deploy:
          requires:
            - build
