version: 0.2

phases:
    build:
        commands:
            - aws deploy push --region ap-northeast-1 --application-name storedresources --s3-location s3://storedresources-codebuild/app --source app
artifacts:
    files:
        - '**/*'
    base-directory: app
    name: storedresources
