version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: script/clean.sh
      runas: root
permissions:
  - object: /var/www/html/app/content/include/
    pattern: "authorize.inc.txt"
    owner: root
    group: root
    mode: 666
    type:
      - file
