version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: script/clean.sh
      runas: root
permissions:
  - object: /var/www/html/app/common/auth/
    pattern: "tokenList.txt",
    owner: root
    group: root
    mode: 666
    type:
      - file
permissions:
  - object: /var/www/html/app/common/auth/
    pattern: "userDataList.txt",
    owner: root
    group: root
    mode: 666
    type:
      - file
